// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Ensure .env is loaded before accessing values
    // In main.dart you should call: await dotenv.load();
    return FirebaseOptions(
      apiKey: dotenv.get('FIREBASE_API_KEY', fallback: ''),
      appId: dotenv.get('FIREBASE_APP_ID', fallback: ''),
      messagingSenderId: dotenv.get('FIREBASE_MESSAGING_SENDER_ID', fallback: ''),
      projectId: dotenv.get('FIREBASE_PROJECT_ID', fallback: ''),
      authDomain: dotenv.get('FIREBASE_AUTH_DOMAIN', fallback: ''),
      storageBucket: dotenv.get('FIREBASE_STORAGE_BUCKET', fallback: ''),
      measurementId: dotenv.get('FIREBASE_MEASUREMENT_ID', fallback: ''),
    );
  }

}